import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RecipeStoreProvider, ThemeProviders } from "./providers/providers";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Recipe Generator Powered By AI",
	description: "Generated by Vira Vakhovska and Viktor Vasylyk",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProviders>
					<Header />
					<RecipeStoreProvider>{children}</RecipeStoreProvider>
					<Footer />
				</ThemeProviders>
			</body>
		</html>
	);
}
